In [1]:
import numpy as np
import pandas as pd
import torch

In [ ]:
a = torch.tensor(1)  # 0d
a

In [ ]:
b = torch.tensor([1, 2, 3])  # 1d
b

In [ ]:
c = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2d
c

In [ ]:
arr = np.array([1, 2, 3])
arr

In [ ]:
arr_tensor = torch.from_numpy(arr)
arr_tensor

In [ ]:
arr[0] = 5

In [ ]:
arr_tensor

# PyTorch. Tensor

## Device

* 'cpu' - процесор
* 'cuda' - Nvidia відеокарта
* 'mps' - Apple M1, M2, M3

# requires_gard

Автоматичний підрахунок градієнтів

In [ ]:
a = torch.tensor(2, dtype=torch.float32, device='cpu', requires_grad=True)

In [ ]:
a.tolist()

In [ ]:
b = torch.tensor(3)

c = a**2
c = c + b

c

In [ ]:
X = torch.arange(1, 201)  # числа від 1 до 200
X = torch.randn(200)   # нормально розподілені числа з середнім=0, стандартне відхилення: 1.5

In [ ]:
c.backward()

In [ ]:
a.grad

In [2]:
from torch import nn

loss_fn = nn.MSELoss()

In [34]:
X = torch.normal(22, 2, size=(200, )).reshape(-1, 1)  # середнє 22, стардатне відхилення 2
display(X.shape)

y = 2.0 * X + 3 + 0.1 * torch.randn(200, 1)
display(y.shape)

# параметр швидкості навчання
learning_rate = 0.01

history = []

# створюємо модель
model = nn.Linear(1, 1)

for epoch in range(21):
    # один крок тренування (пропускаємо X через модель)
    # рух вперед (forward)
    y_pred = model(X)
    
    # рахуємо помилку
    loss = loss_fn(y_pred, y)
    
    # рух назад
    loss.backward()
    
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad
    
    # обнулити градієнти
    model.zero_grad()
    
    history.append({
        "epoch": epoch,
        "loss": loss.item(),
        "weight": model.weight.item(),
        "bias": model.bias.item()
    })

history_df = pd.DataFrame(history)
history_df.head(10)

torch.Size([200, 1])

torch.Size([200, 1])

   epoch          loss        weight          bias
0      0  4.584823e+03  2.900383e+01  5.460372e-01
1      1  3.525647e+05 -2.331907e+02 -1.128539e+01
2      2  2.711225e+07  2.066064e+03  9.247307e+01
3      3  2.084936e+09 -1.809673e+04 -8.174076e+02
4      4  1.603318e+11  1.587162e+05  7.161588e+03
5      5  1.232953e+13 -1.391805e+06 -6.280837e+04
6      6  9.481425e+14  1.220514e+07  5.507773e+05
7      7  7.291230e+16 -1.070301e+08 -4.829922e+06
8      8  5.606964e+18  9.385763e+08  4.235490e+07
9      9  4.311764e+20 -8.230631e+09 -3.714216e+08

In [35]:
history_df.tail(10)

    epoch          loss        weight          bias
11     11  2.549817e+24 -6.329366e+11 -2.856237e+10
12     12  1.960813e+26  5.550393e+12  2.504712e+11
13     13  1.507867e+28 -4.867291e+13 -2.196450e+12
14     14  1.159552e+30  4.268260e+14  1.926127e+13
15     15  8.916971e+31 -3.742953e+15 -1.689073e+14
16     16  6.857163e+33  3.282297e+16  1.481194e+15
17     17  5.273167e+35 -2.878336e+17 -1.298899e+16
18     18           inf  2.524091e+18  1.139040e+17
19     19           inf -2.213444e+19 -9.988553e+17
20     20           inf  1.941029e+20  8.759235e+18