In [11]:
import torch
from torch import nn 
from torch import optim
import pandas as pd
import numpy as np

In [12]:
X = torch.randn(100, 1)
display(X.shape)
y = 3.0 * X + 2.0 + 0.2 * torch.randn(100, 1)
display(y.shape)

torch.Size([100, 1])

torch.Size([100, 1])

In [15]:
model = nn.Linear(1, 1)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)
optimizer = optim.Adam(model.parameters(), lr=0.1)

history = []

for epoch in range(100):
    y_pred = model(X)

    loss = loss_fn(y_pred, y)

    loss.backward()

    optimizer.step()
    optimizer.zero_grad()

    history.append({
        "epoch": epoch,
        "loss": loss.item(),
        "weight": model.weight.item(),
        "bias": model.bias.item()
    })

history = pd.DataFrame(history)
history.head()

   epoch       loss    weight      bias
0      0  12.299222  0.920061 -0.531065
1      1  11.310795  1.019911 -0.431184
2      2  10.365532  1.119502 -0.331509
3      3   9.464125  1.218714 -0.232130
4      4   8.607148  1.317420 -0.133145

In [16]:
history.tail()

    epoch      loss    weight      bias
95     95  0.034462  3.002697  2.009391
96     96  0.034427  3.003158  2.011303
97     97  0.034394  3.003361  2.013166
98     98  0.034361  3.003323  2.014961
99     99  0.034330  3.003066  2.016676